apiVersion: v1
kind: Service
metadata:
  name: my-echo-spring-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-echo-spring
  type: LoadBalancer