apiVersion: v1
kind: DeploymentConfig
metadata:
  name: echo
  namespace: echo-cloud
spec:
  replicas: 1
  selector:
    deployment-config.name: echo
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment-config.name: echo
    spec:
      containers:
        - env:
            - name: ECHO_CLOUD
              value: '0'
            - name: ECHO_CPU
              value: '10'
            - name: SPRING_CONFIG_LOCATION
              value: /deployments/config/application.properties
          image: 'docker-registry.default.svc:5000/echo-cloud/echo'
          imagePullPolicy: Always
          name: default-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /deployments/config
              name: application-config
              readOnly: true
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: application.properties
                path: application.properties
            name: echo-config
          name: application-config
  test: false
  triggers:
    - type: ConfigChange