apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    name: poc-pipeline
  name: poc-pipeline
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node() {
        stage 'deploy-dev'
          openshiftDeploy(namespace: 'poc-dev', deploymentConfig: 'echo')
          openshiftScale(namespace: 'poc-dev', deploymentConfig: 'echo',replicaCount: '2')
        stage 'deploy-qa'
          openshiftDeploy(namespace: 'poc-qa', deploymentConfig: 'echo')
          openshiftScale(namespace: 'poc-qa', deploymentConfig: 'echo',replicaCount: '2')
          }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
